#!/bin/bash

PWD=$(pwd)

#Install dependencies
pip install sh

#Add project to Anaconda path
conda develop $PWD/src &> /dev/null

#Add project to PYTHONPATH path
echo 'export PYTHONPATH="${PYTHONPATH}:'$PWD'/src"' >> ~/.bashrc